//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 03:46:39 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vamdc.org/tapservice/validator/report", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.vamdc.validator.report.schema;
